### ISSUE TITLE
'"port" argument must be >= 0 and < 65536'

### ISSUE THREAD

**Issue by Jonsnow21** [freeCodeCamp/boilerplate-npm#2]
boilerplate-npm $ node server.js 
internal/net.js:17
    throw new RangeError('"port" argument must be >= 0 and < 65536');
    ^

RangeError: "port" argument must be >= 0 and < 65536
    at assertPort (internal/net.js:17:11)
    at Server.listen (net.js:1389:5)
    at EventEmitter.listen (/home/neeraj/meanPractice/boilerplate-npm/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/neeraj/meanPractice/boilerplate-npm/server.js:56:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by bryantvolk** [comment]
you need to set your env PORT variable

on windows in command prompt: set PORT=1234

in unix export PORT=1234
